name: Spotless

on:
  push:
  pull_request:

jobs:
  spotless:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    env:
      GRADLE_OPTS: "-Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.java.installations.auto-download=false"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - 'spotless/**'
              - 'gradle/**'
              - '**/*.gradle'
              - 'settings.gradle'
              - 'gradle.properties'
              - 'dependencies.gradle'
              - 'gradlew'
              - 'gradlew.bat'
              - '.github/**'

      - name: Setup Gradle
        if: steps.filter.outputs.code == 'true'
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Spotless Apply
        if: steps.filter.outputs.code == 'true'
        run: ./gradlew spotlessApply --warning-mode all

      - name: Spotless Apply (2nd pass)
        if: steps.filter.outputs.code == 'true'
        run: ./gradlew spotlessApply --warning-mode all

      - name: Spotless Check
        if: steps.filter.outputs.code == 'true'
        run: ./gradlew spotlessCheck --warning-mode all
        continue-on-error: true
